name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14, 16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - node-version: 10
            os: ubuntu-latest
          - node-version: 12
            os: windows-latest
          - node-version: 14
            os: macos-latest
          - node-version: 16
            os: ubuntu-latest
          - node-version: 18
            os: windows-latest
        exclude:
          - node-version: 16
            os: windows-latest
          - node-version: 18
            os: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      env:
        NODE_ENV: production

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build
      run: npm run build
      env:
        NODE_ENV: production

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14, 16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
      env:
        CI: true

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      run: npm run deploy
      env:
        NODE_ENV: production
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    - name:
      run: echo "This step is missing a name"

  notify:
    runs-on: ubuntu-latest
    needs: [build, lint, deploy]

    steps:
    - name: Notify team
      run: echo "Deployment complete"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Notify team again
      run: echo "Deployment complete again"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
