name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build
      run: npm run build
      env:
        NODE_ENV: production

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
      env:
        CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to production
      run: npm run deploy
      env:
        NODE_ENV: production
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

  notify:
    runs-on: ubuntu-latest
    needs: [build, lint, deploy]

    steps:
    - name: Notify team
      run: echo "Deployment complete"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
